controllers:
    resource:
        path: ../src/Controller/ 
        namespace: App\Controller
    type: attribute
app_profile_index:
    path: /profile
    controller: App\Controller\ProfileController::index
    methods: GET
app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
